---
name: idr0020-barr-chtog
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

######################################################################
# mapr groups
######################################################################
  - group:
      namespace: openmicroscopy.org/mapr/sirna
      columns:
      - name: siRNA Pool Identifier
        clientname: siRNA Identifier
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/sirna/supplementary
      columns:
      - name: siRNA Sequences
        include: yes
      - name: Reagent Design Gene Annotation Build
        include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/sirna
      keys:
      - siRNA Identifier
